name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH로 라즈베리파이 접속 후 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{secrets.USERNAME }}
          key: ${{secrets.SSH_KEY}}
          script: |
            ~/LangChain-Personal-RAG/deploy.sh
